version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GITHUB_REPO_URL=${GITHUB_REPO_URL}
    volumes:
      # Persistent storage for repository, build, and data
      - ./data:/app/.data
      # pnpm cache for faster builds
      - pnpm-store:/root/.pnpm-store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  pnpm-store:
    driver: local
